# This is a basic workflow to help you get started with Actions

name: Generate ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build ISO
        run: /iso-generator.sh /tmp/iso
